name: build-executables
run-name: Building execution files ${{ github.actor }}
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --nowindowed main.py

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/main.exe dist/OrcsCastleDefence.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/main dist/OrcsCastleDefence
          fi
        shell: bash
      - name: Copy sources files
        run: |
          cp -r assets/* dist/;
          cp -r src/* dist/;
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrcsCastleDefence-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Make files executable (Linux)
        run: chmod +x OrcsCastleDefence* || true

      - name: Create GitHub Release
        permissions: write-all
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            OrcsCastleDefence
            OrcsCastleDefence.exe
